version: 2

sources:
  - name: jaffleshop
    database: dbt_workshop
    schema: raw
    tables:
      - name: orders
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        loaded_at_field: _etl_loaded_at
      - name: customers
      - name: payments
